version: "3"
services:
  hmpps-create-electronic-monitoring-order:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-create-electronic-monitoring-order
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  localstack:
    container_name: "localstack-cemo"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - MAIN_CONTAINER_NAME=localstack-cemo
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data/
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/init/ready/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"

networks:
  hmpps:
