version: "3"
services:
  hmpps-create-electronic-monitoring-order:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-create-electronic-monitoring-order

    ##############
    depends_on:
      - cemo-localstack
      - cemo-database
    ##############

    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
    ###########
      - SNS_ENDPOINT_URL=http://localhost:4566
      - SPRING_PROFILES_ACTIVE=stdout,localstack,postgres
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - AWS_DEFAULT_REGION=eu-west-2
    ###########

  cemo-database:
    image: postgres:16
    networks:
      - hmpps
    container_name: cemo-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=cemo-database
      - POSTGRES_USER=cemo-database
      - POSTGRES_DB=cemo-database

  cemo-localstack:
    image: localstack/localstack:3.2
    networks:
      - hmpps
    container_name: cemo-localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      ############
      - SERVICES=sqs,s3
      - DEBUG=1
      - DEFAULT_REGION=eu-west-2
      ############
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps:
